// <auto-generated />
using GrzesioBot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrzesioBot.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20250624212053_AddWebhooks")]
    partial class AddWebhooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("GrzesioBot.AuthorizedUser", b =>
                {
                    b.Property<long>("DiscordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MinecraftUuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DiscordId");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.HasIndex("MinecraftUuid")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GrzesioBot.ChannelWebhook", b =>
                {
                    b.Property<long>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WebhookId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebhookToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChannelId");

                    b.ToTable("Webhooks");
                });
#pragma warning restore 612, 618
        }
    }
}
